FROM node:22-alpine

WORKDIR /app

# Installation des dépendances
COPY package*.json ./
# On installe tout (y compris les devDependencies pour typescript/nodemon)
RUN npm install

# On ne copie pas tout le code ici, on utilisera un volume dans le docker-compose
# pour que les modifications soient instantanées.

EXPOSE 4000

# Commande par défaut (sera surchargée par docker-compose pour inclure Prisma)
CMD ["npm", "run", "dev"]